{"name": "Проверка невозможности логина при некорректно переданном значении пароля или мыла", "status": "passed", "description": "Создаем юзера, подменяем данные на другое значение, логинимся и ожидаем провал", "steps": [{"name": "Создать юзера", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'nrichard@example.com', 'password': 'a(23sUQgeM', 'name': 'Marcus'}"}], "start": 1724590544076, "stop": 1724590544318}, {"name": "Залогиниться под юзером", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'nrichard@example.com12', 'password': 'a(23sUQgeM', 'name': 'Marcus'}"}], "start": 1724590544318, "stop": 1724590544486}], "parameters": [{"name": "altered_field", "value": "'email'"}], "start": 1724590544076, "stop": 1724590544486, "uuid": "72461cb5-7e5a-45b9-9ec9-c43df2de4660", "historyId": "b59903caf896db88762b2be89c3b478a", "testCaseId": "4dbdc073e40df2e74f02f1dbf3ffa28e", "fullName": "tests.test_login_user.TestUserLoginAPI#test_user_login_malformed_data_failure", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestUserLoginAPI"}, {"name": "host", "value": "SlyPC"}, {"name": "thread", "value": "22448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}